/**
 * Full OfficeRnD Flex OAuth2 scope catalogue (name → human description).
 *
 * Surfaced as the selectable checkboxes in Swagger UI's "Authorize" dialog so
 * you can mint a client-credentials token carrying exactly the scopes you pick.
 * Only scopes actually granted to your app in OfficeRnD will succeed — including
 * an ungranted scope makes the whole token request fail.
 */
export const SCOPES = {
  // ── Billing ─────────────────────────────────────────────────────────
  "flex.billing.payments.read": "Read payments",
  "flex.billing.payments.create": "Create payments",
  "flex.billing.payments.methods.read": "Retrieve all payment methods",
  "flex.billing.payments.documents.read": "Read documents associated with the specific invoice",
  "flex.billing.payments.update": "Update payment",
  "flex.billing.payments.allocations.update": "Update allocation accounting",
  "flex.billing.payments.allocations.create": "Create allocations for credit note/overpayment",
  "flex.billing.charges.read": "Read charges",
  "flex.billing.charges.create": "Create charges",
  "flex.billing.charges.update": "Update charges",
  "flex.billing.charges.delete": "Delete charges",
  "flex.billing.checkout.create": "Execute checkout or checkout summary",
  "flex.billing.taxRates.read": "Read tax rates",
  "flex.billing.revenueAccounts.read": "Read revenue accounts",
  "flex.billing.plans.read": "Read plans",
  "flex.billing.resourceRates.read": "Read resource rates",
  "flex.billing.paymentDetails.read": "Read paymentDetails",
  "flex.billing.paymentDetails.create": "Create paymentDetails",
  "flex.billing.paymentDetails.delete": "Delete paymentDetails",
  "flex.billing.paymentGateways.authorize": "Authorize payment intent or setup intent via payment gateway",

  // ── Space ───────────────────────────────────────────────────────────
  "flex.space.bookings.read": "Read bookings",
  "flex.space.bookings.validate": "Validate bookings",
  "flex.space.bookings.create": "Create bookings",
  "flex.space.bookings.update": "Update bookings",
  "flex.space.bookings.delete": "Delete bookings",
  "flex.space.bookings.cancel": "Cancel bookings",
  "flex.space.locations.read": "Read locations",
  "flex.space.floors.read": "Read floors",
  "flex.space.resources.read": "Read resources",
  "flex.space.resourceTypes.read": "Read Resource Types",
  "flex.space.assignments.read": "Read assignments",
  "flex.space.assignments.create": "Create assignments",
  "flex.space.assignments.delete": "Delete assignments",
  "flex.space.amenities.read": "Read amenities",
  "flex.space.passes.read": "Read passes",
  "flex.space.passes.create": "Create passes",
  "flex.space.passes.update": "Update passes",
  "flex.space.passes.delete": "Delete passes",
  "flex.space.credits.read": "Read credits",
  "flex.space.credits.create": "Create credits",
  "flex.space.credits.update": "Update credits",
  "flex.space.credits.delete": "Delete credits",
  "flex.space.coins.read": "Read coins",

  // ── Collaboration ───────────────────────────────────────────────────
  "flex.collaboration.tickets.read": "Read tickets",
  "flex.collaboration.tickets.create": "Create tickets",
  "flex.collaboration.tickets.update": "Update tickets",
  "flex.collaboration.ticketOptions.read": "Read ticket options",
  "flex.collaboration.ticketComments.read": "Read ticket comments",
  "flex.collaboration.ticketComments.create": "Create ticket comments",
  "flex.collaboration.posts.read": "Read posts",
  "flex.collaboration.posts.create": "Create posts",
  "flex.collaboration.posts.delete": "Delete posts",
  "flex.collaboration.events.read": "Read events",
  "flex.collaboration.events.create": "Create events",
  "flex.collaboration.events.update": "Update events",
  "flex.collaboration.events.delete": "Delete events",
  "flex.collaboration.benefits.read": "Read benefits",

  // ── Community ───────────────────────────────────────────────────────
  "flex.community.members.read": "Read members",
  "flex.community.members.create": "Create members",
  "flex.community.members.update": "Update members",
  "flex.community.members.delete": "Delete members",
  "flex.community.members.portalAccess.update": "Manage member portal access",
  "flex.community.companies.read": "Read companies",
  "flex.community.companies.create": "Create companies",
  "flex.community.companies.update": "Update companies",
  "flex.community.companies.delete": "Delete companies",
  "flex.community.visits.read": "Read visits",
  "flex.community.visits.create": "Create visits",
  "flex.community.visits.delete": "Delete visits",
  "flex.community.visitors.read": "Read visitors",
  "flex.community.visitors.create": "Create visitors",
  "flex.community.visitors.delete": "Delete visitors",
  "flex.community.opportunities.read": "Read opportunities",
  "flex.community.opportunities.create": "Create opportunities",
  "flex.community.opportunities.update": "Update opportunities",
  "flex.community.opportunities.delete": "Delete opportunities",
  "flex.community.opportunityStatuses.read": "Read opportunity statuses",
  "flex.community.contracts.read": "Read contracts",
  "flex.community.contracts.update": "Update contracts",
  "flex.community.contracts.create": "Create contracts",
  "flex.community.contracts.delete": "Delete contracts",
  "flex.community.contracts.sign": "Sign contracts",
  "flex.community.contracts.terminate": "Terminate contracts",
  "flex.community.checkins.read": "Read check-ins",
  "flex.community.checkins.create": "Create check-ins",
  "flex.community.checkins.update": "Update check-ins",
  "flex.community.fees.read": "Read fees",
  "flex.community.fees.create": "Create fees",
  "flex.community.fees.update": "Update fees",
  "flex.community.fees.delete": "Delete fees",
  "flex.community.memberships.read": "Read memberships",
  "flex.community.memberships.create": "Create memberships",
  "flex.community.memberships.update": "Update memberships",
  "flex.community.memberships.delete": "Delete memberships",
  "flex.community.receptionFlows.read": "Read reception flows",

  // ── Settings ────────────────────────────────────────────────────────
  "flex.settings.webhooks.read": "Read webhooks",
  "flex.settings.webhooks.create": "Create webhooks",
  "flex.settings.webhooks.update": "Update webhooks",
  "flex.settings.webhooks.delete": "Delete webhooks",
  "flex.settings.customProperties.read": "Read custom properties",
  "flex.settings.secondaryCurrencies.read": "Read secondary currencies",
  "flex.settings.secondaryCurrencies.update": "Update secondary currencies",
  "flex.settings.billing.read": "Read billing settings",
  "flex.settings.integrations.read": "Read integrations",
  "flex.settings.businessHours.read": "Read business hours",
  "flex.settings.organization.read": "Read organization",

  // ── User ────────────────────────────────────────────────────────────
  "flex.user.auth.signup": "Sign up users",
  "flex.user.auth.signin": "Sign in users",
  "flex.user.auth.impersonate": "Impersonate members",
  "flex.user.auth.verify": "Verify token",
  "flex.user.password.update": "Update password",
};
